### ISSUE TITLE
Need to customize `userDataDir `

### ISSUE THREAD

**Issue by djyde** [GoogleChromeLabs/carlo#10]
Instead of hard coded `.profile`, I need:

```js
carlo.launch({
  userDataDir: 'path/to/customDir'
})
```

I can create a PR if needed.

**Comment by rektide** [comment]
(Note: not a maintainer, new to this project.) I didn't understand what this request was about, reading it. I did some looking through the code. I found https://github.com/GoogleChromeLabs/carlo/blob/c3fa0ab717dd12efd146779e7f65712b42f9fbc9/lib/carlo.js#L188 which I think might be what this issue is about.

I agree it would be cool/great/maybe-necssary-sometimes to allow using different browser profiles.

**Comment by djyde** [comment]
@rektide I made a markdown previewer with carlo(https://github.com/djyde/koy). Now every time users run this command, a `.profile` will be created at `cwd`, which is not my expect.

**Comment by pavelfeldman** [comment]
Fixed in https://github.com/GoogleChromeLabs/carlo/commit/8435636d3a2a2d1a5f1023fcd2b3e3e3ac8dcb92

**Comment by pavelfeldman** [comment]
> I can create a PR if needed.

Ah, I should have said yes, missed it.
