### ISSUE TITLE
Allow configurable puppeteer chrome locations

### ISSUE THREAD

**Issue by j** [GoogleChromeLabs/carlo#15]
I want to be able to use this on Lambda / etc and point to a chrome installed in node_modules/*.  Is there a way to have the puppeteer instance options be configurable instead of magically having a chrome instance found or the user providing the puppeteer browser themselves?

**Comment by pavelfeldman** [comment]
Yes, we can expose complete Puppeteer configurability so that you could do those kind of things, including running against bundled Chromium tip of the tree.

Having said that, I've heard that running headful Chrome on Lambda is challenging, so if you want to run things in the cloud, Headless Chrome driven by Puppeteer is your best bet.

**Comment by j** [comment]
Gotcha, yeah I was looking at this as a fancy wrapper on top of Puppeteer at first and for generating screenshots and allowing screenshots of a file that's located in a specific directory without having to start a server.  But after looking more, it's another way of creating desktop apps, etc :P.
