### ISSUE TITLE
Unable to run packaged systeminfo example in osx unless using "sudo"

### ISSUE THREAD

**Issue by sucotronic** [GoogleChromeLabs/carlo#84]
I've download the repo and packed the systeminfo example with no problem. But when I try to start it, as normal user, it show the following error, and then an osx crash screen:

![image](https://user-images.githubusercontent.com/149344/48613478-22013d80-e98c-11e8-927e-32d6fade4350.png)

System: OSX 10.14.1
Pkg: 4.3.4
Chrome: 70.0.3538.77
Carlo:0.9.0

**Comment by pavelfeldman** [comment]
Fixed with https://github.com/GoogleChromeLabs/carlo/commit/0a42a060e3dca2bd10bbd8718ad2bf7aa859dc63 and https://github.com/GoogleChromeLabs/carlo/commit/9faeabcc991428da6aff95961f4f7b9fdbae6518.

[npm](https://www.npmjs.com/package/carlo) 0.9.27 with the fix published.

One needs to specify `localDataDir` for this to work.

**Comment by sucotronic** [comment]
Thanks!!
